services:
  - type: web
    name: pa-ai-salepage
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npx next start -H 0.0.0.0 -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
